import { z } from "zod";

export const contactPlaybooks = ["photography_studio", "iapro"] as const;
export const contactPriorities = ["high", "medium", "low"] as const;
export const contactStatuses = [
  "new",
  "followup_due",
  "discovery",
  "approval_required",
  "billing_review",
] as const;

export const syntheticContactSchema = z.object({
  id: z.string().min(3).max(80),
  tenantId: z.enum(["studio-demo", "iapro-demo"]),
  playbook: z.enum(contactPlaybooks),
  environment: z.literal("synthetic"),
  synthetic: z.literal(true),
  displayName: z.string().min(2).max(120),
  accountName: z.string().min(2).max(160),
  phone: z.string().regex(/^\+593000000\d{3}$/),
  email: z.string().regex(/^[a-z0-9.-]+@example\.invalid$/),
  channel: z.enum(["whatsapp", "email", "form", "spreadsheet"]),
  segment: z.string().min(2).max(100),
  opportunity: z.string().min(2).max(160),
  nextAction: z.string().min(2).max(200),
  estimatedValueUsd: z.number().int().nonnegative(),
  priority: z.enum(contactPriorities),
  status: z.enum(contactStatuses),
  consentStatus: z.literal("not_applicable_synthetic"),
  outboundAllowed: z.literal(false),
  lastInteractionAt: z.string().datetime(),
  dueAt: z.string().datetime(),
  billingState: z.enum(["none", "pending_review", "ready_for_review"]),
});

export type SyntheticContact = z.infer<typeof syntheticContactSchema>;

const seedContacts = [
  {
    id: "studio-test-001",
    tenantId: "studio-demo",
    playbook: "photography_studio",
    environment: "synthetic",
    synthetic: true,
    displayName: "Ana Demo 01",
    accountName: "Familia Maternidad Demo",
    phone: "+593000000001",
    email: "ana.demo01@example.invalid",
    channel: "whatsapp",
    segment: "familia-maternidad",
    opportunity: "Sesión de maternidad",
    nextAction: "Confirmar semana de gestación y fecha preferida",
    estimatedValueUsd: 240,
    priority: "high",
    status: "followup_due",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-27T15:20:00.000Z",
    dueAt: "2026-07-29T18:00:00.000Z",
    billingState: "none",
  },
  {
    id: "studio-test-002",
    tenantId: "studio-demo",
    playbook: "photography_studio",
    environment: "synthetic",
    synthetic: true,
    displayName: "Familia Demo 02",
    accountName: "Retrato Familiar Demo",
    phone: "+593000000002",
    email: "familia.demo02@example.invalid",
    channel: "spreadsheet",
    segment: "familia-reciente",
    opportunity: "Actualización de retrato familiar",
    nextAction: "Preparar borrador de recordatorio estacional",
    estimatedValueUsd: 185,
    priority: "medium",
    status: "approval_required",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-04-12T19:10:00.000Z",
    dueAt: "2026-07-30T16:00:00.000Z",
    billingState: "none",
  },
  {
    id: "studio-test-003",
    tenantId: "studio-demo",
    playbook: "photography_studio",
    environment: "synthetic",
    synthetic: true,
    displayName: "Daniela Demo 03",
    accountName: "Álbum Pendiente Demo",
    phone: "+593000000003",
    email: "daniela.demo03@example.invalid",
    channel: "whatsapp",
    segment: "pendiente-seleccion",
    opportunity: "Selección y diseño de álbum",
    nextAction: "Solicitar revisión humana del trabajo facturable",
    estimatedValueUsd: 115,
    priority: "high",
    status: "billing_review",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-25T21:30:00.000Z",
    dueAt: "2026-07-29T17:30:00.000Z",
    billingState: "ready_for_review",
  },
  {
    id: "studio-test-004",
    tenantId: "studio-demo",
    playbook: "photography_studio",
    environment: "synthetic",
    synthetic: true,
    displayName: "Eventos Demo 04",
    accountName: "Evento Empresarial Demo",
    phone: "+593000000004",
    email: "eventos.demo04@example.invalid",
    channel: "email",
    segment: "corporativo-eventos",
    opportunity: "Cobertura de evento empresarial",
    nextAction: "Completar número de asistentes y horario",
    estimatedValueUsd: 1250,
    priority: "medium",
    status: "discovery",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-28T14:05:00.000Z",
    dueAt: "2026-07-30T15:00:00.000Z",
    billingState: "none",
  },
  {
    id: "studio-test-005",
    tenantId: "studio-demo",
    playbook: "photography_studio",
    environment: "synthetic",
    synthetic: true,
    displayName: "Marca Demo 05",
    accountName: "Catálogo de Productos Demo",
    phone: "+593000000005",
    email: "marca.demo05@example.invalid",
    channel: "form",
    segment: "corporativo-producto",
    opportunity: "Fotografía para catálogo",
    nextAction: "Solicitar cantidad de productos y estilo visual",
    estimatedValueUsd: 680,
    priority: "high",
    status: "new",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-29T12:40:00.000Z",
    dueAt: "2026-07-29T20:00:00.000Z",
    billingState: "none",
  },
  {
    id: "studio-test-006",
    tenantId: "studio-demo",
    playbook: "photography_studio",
    environment: "synthetic",
    synthetic: true,
    displayName: "Colegio Demo 06",
    accountName: "Anuario Escolar Demo",
    phone: "+593000000006",
    email: "colegio.demo06@example.invalid",
    channel: "spreadsheet",
    segment: "institucional-escolar",
    opportunity: "Retratos y anuario escolar",
    nextAction: "Definir cursos, jornadas y entregables",
    estimatedValueUsd: 2100,
    priority: "medium",
    status: "discovery",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-23T17:00:00.000Z",
    dueAt: "2026-07-31T14:00:00.000Z",
    billingState: "none",
  },
  {
    id: "studio-test-007",
    tenantId: "studio-demo",
    playbook: "photography_studio",
    environment: "synthetic",
    synthetic: true,
    displayName: "Pareja Demo 07",
    accountName: "Boda Civil Demo",
    phone: "+593000000007",
    email: "pareja.demo07@example.invalid",
    channel: "whatsapp",
    segment: "social-boda",
    opportunity: "Cobertura de boda civil",
    nextAction: "Confirmar locación y duración de cobertura",
    estimatedValueUsd: 950,
    priority: "high",
    status: "followup_due",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-26T22:15:00.000Z",
    dueAt: "2026-07-29T19:00:00.000Z",
    billingState: "none",
  },
  {
    id: "studio-test-008",
    tenantId: "studio-demo",
    playbook: "photography_studio",
    environment: "synthetic",
    synthetic: true,
    displayName: "Bebé Demo 08",
    accountName: "Recién Nacido Demo",
    phone: "+593000000008",
    email: "bebe.demo08@example.invalid",
    channel: "form",
    segment: "familia-recien-nacido",
    opportunity: "Sesión de recién nacido",
    nextAction: "Solicitar fecha de nacimiento y preferencias",
    estimatedValueUsd: 280,
    priority: "high",
    status: "new",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-29T10:10:00.000Z",
    dueAt: "2026-07-29T18:30:00.000Z",
    billingState: "none",
  },
  {
    id: "studio-test-009",
    tenantId: "studio-demo",
    playbook: "photography_studio",
    environment: "synthetic",
    synthetic: true,
    displayName: "Arquitectura Demo 09",
    accountName: "Inmobiliaria Piloto Demo",
    phone: "+593000000009",
    email: "arquitectura.demo09@example.invalid",
    channel: "email",
    segment: "corporativo-inmobiliario",
    opportunity: "Fotografía de proyecto inmobiliario",
    nextAction: "Confirmar número de espacios y uso de las imágenes",
    estimatedValueUsd: 720,
    priority: "medium",
    status: "approval_required",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-22T13:30:00.000Z",
    dueAt: "2026-08-01T15:00:00.000Z",
    billingState: "none",
  },
  {
    id: "studio-test-010",
    tenantId: "studio-demo",
    playbook: "photography_studio",
    environment: "synthetic",
    synthetic: true,
    displayName: "Video Demo 10",
    accountName: "Testimonio Corporativo Demo",
    phone: "+593000000010",
    email: "video.demo10@example.invalid",
    channel: "spreadsheet",
    segment: "corporativo-video",
    opportunity: "Video testimonial",
    nextAction: "Revisar guion y registrar ítem facturable",
    estimatedValueUsd: 780,
    priority: "medium",
    status: "billing_review",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-20T16:45:00.000Z",
    dueAt: "2026-07-30T17:00:00.000Z",
    billingState: "pending_review",
  },
  {
    id: "iapro-test-001",
    tenantId: "iapro-demo",
    playbook: "iapro",
    environment: "synthetic",
    synthetic: true,
    displayName: "Administración Demo 01",
    accountName: "Urbanización Horizonte Demo",
    phone: "+593000000011",
    email: "administracion.demo01@example.invalid",
    channel: "form",
    segment: "urbanizacion-mantenimiento",
    opportunity: "Plan maestro de mantenimiento",
    nextAction: "Solicitar inventario técnico y frecuencia de fallas",
    estimatedValueUsd: 1450,
    priority: "high",
    status: "discovery",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-29T11:15:00.000Z",
    dueAt: "2026-07-29T21:00:00.000Z",
    billingState: "none",
  },
  {
    id: "iapro-test-002",
    tenantId: "iapro-demo",
    playbook: "iapro",
    environment: "synthetic",
    synthetic: true,
    displayName: "Tesorería Demo 02",
    accountName: "Condominio Río Demo",
    phone: "+593000000012",
    email: "tesoreria.demo02@example.invalid",
    channel: "email",
    segment: "propiedad-horizontal-cartera",
    opportunity: "Rediseño del proceso de cartera",
    nextAction: "Levantar antigüedad de saldos y reglas actuales",
    estimatedValueUsd: 980,
    priority: "high",
    status: "followup_due",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-26T18:10:00.000Z",
    dueAt: "2026-07-29T19:30:00.000Z",
    billingState: "none",
  },
  {
    id: "iapro-test-003",
    tenantId: "iapro-demo",
    playbook: "iapro",
    environment: "synthetic",
    synthetic: true,
    displayName: "Operaciones Demo 03",
    accountName: "Clínica Piloto Demo",
    phone: "+593000000013",
    email: "operaciones.demo03@example.invalid",
    channel: "form",
    segment: "salud-procesos",
    opportunity: "Levantamiento de procesos operativos",
    nextAction: "Definir proceso crítico, volumen y responsables",
    estimatedValueUsd: 1280,
    priority: "medium",
    status: "new",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-29T13:05:00.000Z",
    dueAt: "2026-07-30T16:00:00.000Z",
    billingState: "none",
  },
  {
    id: "iapro-test-004",
    tenantId: "iapro-demo",
    playbook: "iapro",
    environment: "synthetic",
    synthetic: true,
    displayName: "Producción Demo 04",
    accountName: "Planta Andina Demo",
    phone: "+593000000014",
    email: "produccion.demo04@example.invalid",
    channel: "spreadsheet",
    segment: "industrial-automatizacion",
    opportunity: "Valoración de automatización",
    nextAction: "Cuantificar horas manuales, errores y retrabajos",
    estimatedValueUsd: 1750,
    priority: "high",
    status: "approval_required",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-24T14:50:00.000Z",
    dueAt: "2026-07-30T18:00:00.000Z",
    billingState: "none",
  },
  {
    id: "iapro-test-005",
    tenantId: "iapro-demo",
    playbook: "iapro",
    environment: "synthetic",
    synthetic: true,
    displayName: "Gerencia Demo 05",
    accountName: "Hotel Faro Demo",
    phone: "+593000000015",
    email: "gerencia.demo05@example.invalid",
    channel: "email",
    segment: "hotel-gestion-operativa",
    opportunity: "Estandarización de operación",
    nextAction: "Priorizar limpieza, mantenimiento y compras",
    estimatedValueUsd: 1320,
    priority: "medium",
    status: "discovery",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-21T12:20:00.000Z",
    dueAt: "2026-07-31T16:30:00.000Z",
    billingState: "none",
  },
  {
    id: "iapro-test-006",
    tenantId: "iapro-demo",
    playbook: "iapro",
    environment: "synthetic",
    synthetic: true,
    displayName: "Proyectos Demo 06",
    accountName: "Constructora Prisma Demo",
    phone: "+593000000016",
    email: "proyectos.demo06@example.invalid",
    channel: "form",
    segment: "construccion-proyectos",
    opportunity: "Control de avance y contratistas",
    nextAction: "Solicitar cronograma, presupuesto y reportes actuales",
    estimatedValueUsd: 1600,
    priority: "medium",
    status: "new",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-29T09:35:00.000Z",
    dueAt: "2026-07-30T14:30:00.000Z",
    billingState: "none",
  },
  {
    id: "iapro-test-007",
    tenantId: "iapro-demo",
    playbook: "iapro",
    environment: "synthetic",
    synthetic: true,
    displayName: "Seguridad Demo 07",
    accountName: "Centro Comercial Piloto Demo",
    phone: "+593000000017",
    email: "seguridad.demo07@example.invalid",
    channel: "email",
    segment: "comercial-seguridad",
    opportunity: "Matriz de riesgos y contingencia",
    nextAction: "Solicitar planos, incidentes y controles actuales",
    estimatedValueUsd: 1180,
    priority: "high",
    status: "followup_due",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-25T15:40:00.000Z",
    dueAt: "2026-07-29T20:30:00.000Z",
    billingState: "none",
  },
  {
    id: "iapro-test-008",
    tenantId: "iapro-demo",
    playbook: "iapro",
    environment: "synthetic",
    synthetic: true,
    displayName: "Talento Demo 08",
    accountName: "Fundación Norte Demo",
    phone: "+593000000018",
    email: "talento.demo08@example.invalid",
    channel: "spreadsheet",
    segment: "servicios-manuales",
    opportunity: "Manual de funciones y procedimientos",
    nextAction: "Confirmar estructura, cargos y documentos existentes",
    estimatedValueUsd: 860,
    priority: "medium",
    status: "approval_required",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-19T17:55:00.000Z",
    dueAt: "2026-08-01T17:00:00.000Z",
    billingState: "none",
  },
  {
    id: "iapro-test-009",
    tenantId: "iapro-demo",
    playbook: "iapro",
    environment: "synthetic",
    synthetic: true,
    displayName: "Analítica Demo 09",
    accountName: "Distribuidora Piloto Demo",
    phone: "+593000000019",
    email: "analitica.demo09@example.invalid",
    channel: "form",
    segment: "distribucion-inteligencia",
    opportunity: "Dashboard de indicadores",
    nextAction: "Definir decisiones, fuentes y frecuencia de actualización",
    estimatedValueUsd: 1040,
    priority: "medium",
    status: "discovery",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-28T16:25:00.000Z",
    dueAt: "2026-07-31T15:30:00.000Z",
    billingState: "none",
  },
  {
    id: "iapro-test-010",
    tenantId: "iapro-demo",
    playbook: "iapro",
    environment: "synthetic",
    synthetic: true,
    displayName: "Tecnología Demo 10",
    accountName: "Servicios Delta Demo",
    phone: "+593000000020",
    email: "tecnologia.demo10@example.invalid",
    channel: "email",
    segment: "servicios-tecnologia",
    opportunity: "Diagnóstico tecnológico",
    nextAction: "Inventariar sistemas, integraciones y fallas",
    estimatedValueUsd: 920,
    priority: "high",
    status: "billing_review",
    consentStatus: "not_applicable_synthetic",
    outboundAllowed: false,
    lastInteractionAt: "2026-07-23T11:45:00.000Z",
    dueAt: "2026-07-30T19:00:00.000Z",
    billingState: "pending_review",
  },
] as const;

export const syntheticContacts = Object.freeze(
  z.array(syntheticContactSchema).parse(seedContacts),
);
